POST http://localhost:5000/task/
Content-Type: application/json

{
    "isDone": false,
    "userId": 45,
    "value": "Some new task to do!!!",
    "deadline": "2022-01-17",
    "createdAt": "2022-01-15",
    "updatedAt": "2022-01-15"
}